name = "api"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[r2_buckets]]
binding = "UPLOAD_BUCKET"
bucket_name = "upload-bucket"

